name: $(version)

trigger:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Chartmuseum
- group: S3Bucket
- name: imageName
  value: 'infolink'
- name: version
  value: $[format('3.0.{0}', counter('3.0', 0))]

jobs:

- job: dotnet
  displayName: build, test and pack nuget
  steps:

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 3.1.100'
    inputs:
      packageType: sdk
      version: 3.1.100
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/*.csproj'
      arguments: '--configuration Release'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: pack
      packagesToPack: 'SW.Infolink.Sdk/SW.Infolink.Sdk.csproj;'
      nobuild: true
      versioningScheme: byBuildNumber

  - task: NuGetCommand@2
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'swnuget' 

- job: build
  displayName: Build, push image and chart and deploy to playground
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')
  steps:

  - task: VersionDotNetCoreAssemblies@2
    inputs:
      Path: '$(Build.SourcesDirectory)'
      VersionNumber: '$(Build.BuildNumber)'
      Injectversion: False
      VersionRegex: '\d+\.\d+\.\d+'
      FilenamePattern: '.csproj'
      SDKNames: 'Microsoft.NET.Sdk'
      OutputVersion: 'OutputedVersion'

  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(imageName)
      dockerfile: $(Build.SourcesDirectory)/Dockerfile
      containerRegistry: simplyworksacr
      tags: |
        $(version)
        latest

  - task: HelmInstaller@0
    displayName: 'Install Helm 3.2.4'
    inputs:
      helmVersion: '3.2.4'
      checkLatestHelmVersion: false
      installKubectl: false

  - task: HelmDeploy@0
    displayName: Helm package
    inputs:
      command: package
      chartPath: charts/default
      arguments: --version $(version) --app-version $(version)
      updatedependency: true

  - task: Bash@3
    displayName: 'Upload to chart museum'
    inputs:
      targetType: 'inline'
      script: |
        for f in $(Build.ArtifactStagingDirectory)/*.tgz
        do 
          echo "Uploading @$f"
          curl --data-binary "@$f" https://charts.sf9.io/api/charts --user $(CmUser):$(CmPassword)
        done 

  - task: HelmDeploy@0
    displayName: 'Deploy to playground'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'k8s-s9'
      namespace: 'playground'
      command: 'upgrade'
      chartName: '$(imageName)'
      chartVersion: $(version)
      releaseName: '$(imageName)'
      overrideValues: 'db=$(dbConnection),ingress.enabled=true,ingress.hosts={infolink.sf9.io},global.bus.rabbitUrl=$(rabbitUrl),global.cloudFiles.secretAccessKey=$(SecretAccessKey),global.cloudFiles.accessKeyId=$(AccessKeyId),global.cloudFiles.serviceUrl=$(ServiceUrl),global.cloudFiles.bucketName=$(BucketName)'
      arguments: --repo https://charts.sf9.io
