# Default values for project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# fullnameOverride: blankcrm
replicaCount: 1

image:
  pullPolicy: IfNotPresent

# imagePullSecrets:
#   - name: sw-secret
  # Optionally specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  #
  # This uses credentials from secret "myRegistryKeySecretName".
  # - name: myRegistryKeySecretName
service:
  type: ClusterIP
  port: 80

probes:
  enabled: false

ingress:
  enabled: false
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
secrets: 

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# db is the connection string for the database
db: ""

dbConnectionStringName: ConnectionStrings__InfolinkDb

dbType: "mysql"
adminDb: "defaultdb"
serverlessCommandTimeout: ''
documentPrefix: 'temp30/infolinkdocs'
storageProvider: ''
areXChangeFilesPrivate: 'false'

global:

  environment: Development

  token:
    key: '6547647654764764767657658658758765876532542'
    issuer: local
    audience: local

  logger:
    esUrl: ""
    esUser: ""
    esPassword: ""

  bus:
    rabbitUrl: ""

  cloudFiles:
    accessKeyId: ""
    secretAccessKey: ""
    serviceUrl: ""
    bucketName: ""
    
rabbitmq:
  enabled: false
  auth:
    username: ''
    password: ''
  ingress:
    enabled: 'true'
    extraHosts:
      - name: ''
        path: ''
    


