{{- if .Values.ingress.enabled -}}
{{- $fullName := include "project.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "project.name" . }}
    chart: {{ template "project.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

  annotations:
  {{- if ne $ingressPath "/"}}
    nginx.ingress.kubernetes.io/rewrite-target: /$2 
  {{- end -}}
{{- with .Values.ingress.annotations }}    


{{ toYaml . | indent 4 }}
{{- end }}


spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }} 
      http:
        paths:
        {{- if ne $ingressPath "/"}}
        - path: "{{ $ingressPath }}(/|$)(.*)"
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
        {{ else }}
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
        {{- end -}}
  {{- end }}
{{- end }}
