apiVersion: v1
kind: Secret
metadata:
  name: {{ template "project.fullname" . }}
data:
  db: {{ .Values.db | b64enc }} 
  tokenKey: {{ .Values.global.token.key | b64enc }} 
  tokenIssuer: {{ .Values.global.token.issuer | b64enc }} 
  tokenAudience: {{ .Values.global.token.audience | b64enc }} 
  rabbitUrl: {{ .Values.global.bus.rabbitUrl | b64enc }} 

  {{- if .Values.global.logger.esUrl }}
  esUrl: {{ .Values.global.logger.esUrl | b64enc }}
  {{- end }}

  {{- if .Values.global.logger.esUser }}
  esUser: {{ .Values.global.logger.esUser | b64enc }}
  {{- end }}

  {{- if .Values.global.logger.esPassword }}
  esPassword: {{ .Values.global.logger.esPassword | b64enc }}
  {{- end }}

  {{- $root := . }}
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}


