<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <RootNamespace>SW.Bitween.Adapters.Bus.Sqs</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.SQS" Version="3.7.400.87" />
    <PackageReference Include="SimplyWorks.Serverless.Sdk" Version="8.1.14" />
  </ItemGroup>
</Project>
