<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SW.Bitween.MySql</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.30">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\SW.Bitween.Api\SW.Bitween.Api.csproj" />
    <PackageReference Include="SimplyWorks.Scheduler.MySql" Version="8.1.8" />
  </ItemGroup>
  

  

</Project>
