<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SW.Bitween.SampleResidentHandler</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SimplyWorks.Serverless.Sdk" Version="8.1.19" />
  </ItemGroup>

</Project>
